### ISSUE TITLE
cambio nome sito

### ISSUE THREAD

**Issue by forzuto-mangione** [thezingaro/didattica-online-website#2]
Sarebbe utile se l'indirizzo del sito NON fosse:
https://jovial-hypatia-56b340.netlify.com/
ma fosse

https://didatticaonline.netlify.com/
oppure 
https://emergenzadidatticaonline.netlify.com/

Grazie!

**Comment by lozingaro** [comment]
Assumendo che la priorità sia la seguente:
1. didatticaonline
2. emergenzadidatticaonline

la pagina è ora visitabile all'indirizzo [https://didatticaonline.netlify.com/](https://didatticaonline.netlify.com/)
