### ISSUE TITLE
Commenti ai post

### ISSUE THREAD

**Issue by forzuto-mangione** [thezingaro/didattica-online-website#4]
Sarebbe fantastico se le persone potessero inserire dei commenti ai post che inserisco.

**Comment by lozingaro** [comment]
[https://desiredpersona.com/disqus-comments-jekyll/](https://desiredpersona.com/disqus-comments-jekyll/)

**Comment by forzuto-mangione** [comment]
Non penso di essere riuscita a far funzionare la cosa come dovrebbe..
